services:
  - type: web
    name: epilepsy-neuro-ai
    env: python
    buildCommand: "pip install --upgrade pip && pip install --only-binary=:all: -r web_app/requirements.txt"
    startCommand: "cd web_app && gunicorn app:app --timeout 120 --workers 1"
    plan: free
