services:
  - type: web
    name: epilepsy-neuro-ai
    runtime: python
    buildCommand: "pip install -r web_app/requirements.txt"
    startCommand: "cd web_app && python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
    plan: free
